version: '3'

volumes:
  postgres:
  postgis-data:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:13
      container_name: keycloak_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  kpi_db:
    image: postgres:13
    container_name: kpi_db
    environment:
      POSTGRES_DB: kpi
      POSTGRES_USER: kpi
      POSTGRES_PASSWORD: kpi
      PGDATA: "/data/kpi/postgres"
    volumes:
       - postgres:/data/kpi/postgres
    ports:
       - "15432:5432"
    restart: unless-stopped
  geospatial:
    image: kartoza/postgis:14-3.1
    container_name: geo_db
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=geospatial
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      hostname: tamky.xyz
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
