
server:
  port: 8093
  servlet:
    context-path: /mytamky   
base-url: http://www.tamky.xyz:${server.port}/${server.servlet.context-path}    
keycloak-client:
  server-url: http://tamky.xyz:8080/auth
  realm:  Smartcity
spring:
  application:
    name: ui-service 
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ui-service
            public-client: true
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/