version: '3.3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "TrackTemperature:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /opt/data/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083" # Admin interface
      - "8086:8086" # HTTP API
      - "8090:8090"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - influxdb-storage:/var/lib/influxdb

# InfluxDB admin UI
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    links:
      - influxdb:influxdb
    volumes:
      - chronograf-storage:/var/lib/chronograf

volumes:
  influxdb-storage:
  chronograf-storage: